const DATA = [
  {
    id: "1",
    title: "Pousette single en trés bonne état",
    content: "Hello content",
    nbImg: 3,
    mainImg: require("../assets/announcements/1/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "2",
    title: "Armoire",
    content: "Hello content",
    nbImg: 2,
    mainImg: require("../assets/announcements/2/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "3",
    title: "Bequille",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/3/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "4",
    title: "Bibliothèque IKEA HEMNES",
    content: "Hello content",
    nbImg: 2,
    mainImg: require("../assets/announcements/4/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "5",
    title: "Canapé Beige",
    content: "Hello content",
    nbImg: 2,
    mainImg: require("../assets/announcements/5/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "6",
    title: "Chaises en bois",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/6/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "7",
    title: "CoiffeurRelooking homme -Conseil en image 15 euros à domicile",
    content: "Hello content",
    nbImg: 2,
    mainImg: require("../assets/announcements/7/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "8",
    title: "Cours de soutien maths",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/8/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "9",
    title: "Cuisine",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/9/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "10",
    title: "Fauteuil roulant",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/10/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "11",
    title: "Fauteuil roulant semi automatic",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/11/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "12",
    title: "Fauteuils de bureau neufs",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/12/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "13",
    title: "FrançaisSoutien scolaire par Enseignante",
    content: "Hello content",
    nbImg: 1,
    mainImg: require("../assets/announcements/13/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
  {
    id: "14",
    title: "Table salle à manger",
    content: "Hello content",
    nbImg: 3,
    mainImg: require("../assets/announcements/14/1.jpg"),
    city: "Casablanca",
    created_at: "12 déc, 09:45",
  },
];

export default DATA;
